# 格式说明：
# 普通替换：源文本(2+空格)目标文本
# 正则替换：REGEX:模式(2+空格)替换文本
zh-CN       zh-TW
隻讀        只讀
隻影響      只影響
隻是        只是
軟件        軟體
代碼        程式碼
程序        程式
項目        專案
併合並      並合併
合並        合併
復雜        複雜
提交併      提交並
髮送        發送
REGEX:(?<!合)併為  並為
幹浄        乾淨
併發        並發
要求籤名    要求簽名
軟體包      軟件包
智能體      AI 代理
事故        異常事件
展開全部     顯示全部
發佈        發布
圖標        圖示
鼠標        滑鼠
內存        記憶體
硬盤        硬碟
卸載        解除安裝
窗口        視窗
屏幕        螢幕
網絡        網路
導航        導航
菜單        選單
服務器      伺服器
數據        資料
視頻        視訊
音頻        音訊
鍵入        輸入
郵箱        信箱
郵件地址     電子郵件
密鑰        金鑰
星標        星號
分叉        分支
關注        追蹤
搜索        搜尋
文檔        文件
鏈接        連結
信息        訊息
後臺        後台
前臺        前台
運行        執行
反饋        回饋
發行版      發行版本
插件        外掛
洞察        分析
登錄        登入
默認        預設
文件夾      資料夾
文件名      檔名
剪貼簿      剪貼簿
克隆        複製
倉庫        儲存庫
拉取請求    合併請求
複刻        Fork
賬號        帳號
賬單        帳單
賬戶        帳戶
打印        列印
模板        範本
緩存        快取
界面        介面
添加        新增
源碼        原始碼
調試        除錯
域名        網域
周期        週